### ISSUE TITLE
Table rendered empty on init

### ISSUE THREAD

**Issue by Catscratch** [Maxl94/ngx-multi-sort-table#121]
Hi.

I have the problem, that the table is rendered empty on component init. It consumes the right space, but the cells are empty.

After hiding and showing a column, everything is working fine.

Here is an example, ignore the mat-icon not working.
https://stackblitz.com/edit/stackblitz-starters-z6b486

**Comment by Catscratch** [comment]
I found the issue. I cannot asign the columns later with tableData.columns, I have to assign it in the constructor of TableData.

Then everything is working. Not sure it is intended or a bug.

**Comment by Maxl94** [comment]
Thanks for submission of the issue. I close this due to the bug report #122
