### ISSUE TITLE
Angular 9 compatibility issue

### ISSUE THREAD

**Issue by CarstenHouweling** [Maxl94/ngx-multi-sort-table#13]
Angular 9 uses the Ivy compiler per default which makes using ngx-multi-sort-table problematic.

The error :

```
ERROR in Failed to compile entry-point ngx-mat-multi-sort (module as esm5) due to compilation errors:
node_modules/ngx-mat-multi-sort/fesm5/ngx-mat-multi-sort.js:924:30 - error NG1010: Value at position 1 in the NgModule.imports of MatMultiSortModule is not a reference: [object Object]

924                     imports: [
                                 ~
925                         CommonModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
935                         MatTooltipModule
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
936                     ]
    ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Maxl94** [comment]
The packages has actually no official supported for angular 9 and angular material 9. I will add this later, but I think this will by middle of the year, when we upgrade our projects.

Feel free to make a pull request.

**Comment by ArcMarky** [comment]
Hi @Maxl94 , Any updates on this? Thanks.

**Comment by Maxl94** [comment]
Sorry, I currently don't have the time to maintainte. I plane to update this August or September. Or feel free to make a pull request.

**Comment by AP12345678** [comment]
Hello  @Maxl94 Any plan to update this. We have to upgrade our project to angular 9. 
Also angular 10 is out, we have to keep updating ng libs.

**Comment by Maxl94** [comment]
Hi currently there is no progress. I still hope that I will have time to maintaine in september. @AP12345678 feel free to fix it your self an make a pull request.

**Comment by Maxl94** [comment]
There is now a angular 10 version of this library (Version 0.2.0). I will skipp angular 9. Maybe the angular 10 version is backward compatible to angular 9. I have not tested this.
