### ISSUE TITLE
Why do we need to initialize datasource inside setTimeout?

### ISSUE THREAD

**Issue by Pacn91** [Maxl94/ngx-multi-sort-table#14]
Hi!
Can you explain why we need to initialize the _datasource_ inside setTimeout?
``` 
setTimeout(() => {
  this.table.dataSource = new MatMultiSortTableDataSource(this.sort);
  this.getData();
}, 0);
```

**Comment by Maxl94** [comment]
I just I to avoid `Expression has changed after it was checked` Error. That might not be necessary

**Comment by Pacn91** [comment]
Humm ok thks. I'm trying to implement the **Table retrieving data through HTTP** from Angular Material Docs with your library, but I'm getting this error when initializing the dataSource. 
![Screenshot_1](https://user-images.githubusercontent.com/17788348/75972135-c7665a80-5eca-11ea-8197-2de3740171e4.png)

Do you know why?
I leave you with my code:
```
ngAfterViewInit(){
    setTimeout(() => {
      this.table.dataSource = new MatMultiSortTableDataSource(this.sort, false);
    }, 0);
    
    this.sort.sortChange.subscribe(() => { this.paginator.pageIndex = 0 });

    merge(this.sort.sortChange, this.paginator.page)
      .pipe(
        startWith({}),
        switchMap(() => {
          this.isLoading = true;
          return this.userManagementService.getTableData(
            this.paginator.pageIndex,
            this.paginator.pageSize,
            this.table.sortParams,
            this.table.sortDirs
          );
        }),
        map(res => {
          this.isLoading = false;
          this.resultsLength = res.totalUsers;
          return res.table;
        }),
        catchError(() => {
          this.isLoading = false;
          return of([]);
        })
      ).subscribe(
        res => {
          this.table.dataSource.data = res;
        }
      );
```

Thanks in advance

**Comment by Pacn91** [comment]
Also, if I initialize the dataSource on the ngOnInit without the setTimeout I get these errors: 
![Screenshot_2](https://user-images.githubusercontent.com/17788348/75975959-5fffd900-5ed1-11ea-8578-c35c888b8562.png)

```
ngOnInit(){
   ...
   this.table.dataSource = new MatMultiSortTableDataSource(this.sort, false);
}

ngAfterViewInit(){
    this.sort.sortChange.subscribe(() => { this.paginator.pageIndex = 0 });

    merge(this.sort.sortChange, this.paginator.page)
      .pipe(
        startWith({}),
        switchMap(() => {
          this.isLoading = true;
          return this.userManagementService.getTableData(
            this.paginator.pageIndex,
            this.paginator.pageSize,
            this.table.sortParams,
            this.table.sortDirs
          );
        }),
        map(res => {
          this.isLoading = false;
          this.resultsLength = res.totalUsers;
          return res.table;
        }),
        catchError(() => {
          this.isLoading = false;
          return of([]);
        })
      ).subscribe(
        res => {
          this.table.dataSource.data = res;
        }
      );
```

**Comment by Maxl94** [comment]
Can you debug how your `res` looks like?

```
      ).subscribe(
        res => {
          this.table.dataSource.data = res;  \\<== looks more like your value is not what data expects.
        }
      );
```

I also suggest to use `this.table.data = res.users;` instead of ` this.table.dataSource.data = res;`.

**Comment by Pacn91** [comment]
Ok I updated to `this.table.data = res;`

The response I'm getting is the following: 
![Screenshot_3](https://user-images.githubusercontent.com/17788348/75977790-0ac5c680-5ed5-11ea-9e32-67bbe6be425b.png)

I think the problem is that the response takes time to arrive so its gives that error, but I'm not sure. What do you think?

**Comment by Maxl94** [comment]
I think it's not a problem or bug of this package. You might find an answer on stackoverlow for the question.

If you still think it's a bug, than open a new Issue with detailed information. Thanks!

**Comment by Pacn91** [comment]
Okey thanks mate ;)
