### ISSUE TITLE
Move Menu Items only on 6-Dots Icon

### ISSUE THREAD

**Issue by Catscratch** [Maxl94/ngx-multi-sort-table#165]
When on a mobile device, you can't use the mouse wheel to scroll.

Therefore, when the context menu gets large it will end outside the screen and you're not able to reach all entries. Every touch-move will result in a reordering of the menu.

My suggestion would be, wo just enable the reordering when you grap the 6-dots icon and leave the rest to default Angular checkbox behavior.

![image](https://github.com/Maxl94/ngx-multi-sort-table/assets/1955624/747d67cb-6a86-43fe-a6e7-3b08c2edb77d)

Also, the css class of the 6-dots icon should be ```cursor: grab```

Would that be possible?

**Comment by ruempel** [comment]
Consider this: https://github.com/Maxl94/ngx-multi-sort-table/pull/168
