### ISSUE TITLE
Compatible version with angular 14

### ISSUE THREAD

**Issue by captain-shubhanshu** [Maxl94/ngx-multi-sort-table#186]
Hi, I'm planning to upgrade my angular project from v13 to v14 but I'm getting the following error:
`Package "ngx-mat-multi-sort" has an incompatible peer dependency to "@angular/common" (requires "^12.0.2" (extended), would install "14.3.0").
Migration failed: Incompatible peer dependencies found.`

Can you please let me know how can I resolve this?

**Comment by Catscratch** [comment]
Which version of ngx-mat-muti-sort are you using? Seems like an old one.

**Comment by captain-shubhanshu** [comment]
> Which version of ngx-mat-muti-sort are you using? Seems like an old one.

This is what I've in the package.json-
`"ngx-mat-multi-sort": "^0.7.4"`

**Comment by Catscratch** [comment]
Please upgrade your version.

See here: https://github.com/Maxl94/ngx-multi-sort-table/releases

**Comment by captain-shubhanshu** [comment]
That I already but specifically to which version?

**Comment by Catscratch** [comment]
You could try https://github.com/Maxl94/ngx-multi-sort-table/releases/tag/v0.10.2

But if you're in the middle of the Angular update process anyway, you can also try using ```ng update @angular/core@14 @angular/cli@14 --force``` to get rid of the error.

As soon as you reached your Angular target version (would recommend 17) you can just use the latest version of ngx-multi-sort-table.

**Comment by captain-shubhanshu** [comment]
Okay so as I'm planning to upgrade my application to the latest angular version, not upgrading the `ngx-mat-multi-sort` package won't have any effects if I'm using it.

**Comment by Catscratch** [comment]
As soon as you reached Angular 17, you should upgrade ngx-mat-multi-sort to the latest version (currently 17.1.0).
