### ISSUE TITLE
Aria-Sort not correctly set before sorting

### ISSUE THREAD

**Issue by fanalin** [Maxl94/ngx-multi-sort-table#189]
The aria-sort attribute of the th is a bunch of javascript when the column hasn't been ordered by.

![Bildschirmfoto 2024-03-28 um 14 38 18](https://github.com/Maxl94/ngx-multi-sort-table/assets/2435068/85a35547-b5a1-4ca8-b6c4-2182ccf8e36f)

`aria-sort="_getAriaSortAttribute() {
    if (!this._isSorted()) {
      return &quot;none&quot;;
    }
    return this.getSortDirection() === &quot;asc&quot; ? &quot;ascending&quot; : &quot;descending&quot;;
  }"`

When I click on the column header, the javascript is correctly executed and the aria-sort attribute is set to ascending/descending.

Tested with the latest angular, angular-material (17.3) and ngx-mat-multi-sort (17.1.0), but issue is also found in older versions.

**Comment by Catscratch** [comment]
Can confirm this. Not sure if the binding is still needed. I created a PR and will ask Max to have a look.

**Comment by Catscratch** [comment]
It's merged. But since it does not affect the runtime atm, I decided to not build a hotfix version for that. It will be part of the next regular release.
