### ISSUE TITLE
Add filtering to MatTableDataSource 

### ISSUE THREAD

**Issue by Maxl94** [Maxl94/ngx-multi-sort-table#37]
filtering is present in MatTableDataSource and not in DataSource.  Basically, for filtering any data we will use below logic with MatTableDataSource .. 

searchText :""   --> we get this input from html on a key stroke on search field

dataSource: MatTableDataSource<someArray>;

this.dataSource.filter === searchText

now the dataSource will have the filtered value and the same is returned to html

_Originally posted by @Rakshith-hv in https://github.com/Maxl94/ngx-multi-sort-table/issues/33#issuecomment-764800630_

**Comment by wujunyu** [comment]
Thanks for your code.

To add filter feature, I have simply migrate source code from MatTableDataSource from Angular components

**Comment by Maxl94** [comment]
@wujunyu you can create a PR if you like.
