### ISSUE TITLE
Stop menu from closing on column toggle

### ISSUE THREAD

**Issue by Lotec724** [Maxl94/ngx-multi-sort-table#40]
Hello,

I would like to discuss the issue of the column select dropdown closing on every toggle. When a user tries to toggle many columns at once this becomes quite tedious, as he has to reopen the mat-menu for every column. I did some experimenting and found a working solution by adding a (click)="$event.stopPropagation()" to the "example-box" divs in the mat-multi-sort-table-settings.component.html:25.

`<div class="example-box" *ngFor="let column of _tableData.columns" cdkDrag (click)="$event.stopPropagation()">`

This might not be the preferred behavior for everyone, so it would probably be a better idea to provide an optional @Input to set this behaviour. Let me know what you think and I will gladly provide a PR if needed.

**Comment by Maxl94** [comment]
I think this is pretty good idea. I have not tested your implementation yet. It feels a little hacky. But so far I have not seen another way to prevent the menu from closing. The angular material docs show no property to control that.

I currently  think about replacing the menu with a dialog. That would be much more flexible. It's just an idea, what do you think? Maybe that's kind of overkill. 

To come back to your point. I definitively agree to make that behavior option, default should be "off". Create a PR if you like, I plan to a release next week.

**Comment by Lotec724** [comment]
Yes it certainly feels a little hacky. A proper dialog would probably be the cleanest and most flexible solution, I will test this out a bit on Monday and get back to you. Thanks for the quick reply :)

**Comment by Lotec724** [comment]
So I did some testing and was able to setup a dialog instead of the mat-menu. For this I setup a new component mat-multi-sort-column-dialog, which contains the cdkDropList. I also added a new @Input "closeDialogOnChoice" (there is probably a better name for this), which toggles the behavior of the dialog on selecting an option (if it should close or not). The settings component opens the dialog and injects the required data.

Since the dialog should behave like a menu, I first tried to set hasBackdrop: false in the MatDialogOptions but this also disables closing the dialog on a click outside the component. So I used a transparent backdrop class instead. For the position of the dialog I set an id on the toggle button and used its left and top offset as starting position. 

There is still an issue with some CSS though. By default the .mat-dialog-container has a padding of 24px, which is not desired in this case. I defined a custom panelClass for the dialog to overwrite this behavior, but as per the documentation the styles for this class should be set in a global scope (so in styles.scss). This is because the dialog is part of the overlay container and styles would not get applied otherwise. There is a solution using ::ng-deep, but that is deprecated. It also works by setting "encapsulation: ViewEncapsulation.None" in the dialog component, but I'm not sure yet if this would have any unwanted sideeffects when using the library in a project. 

I pushed this solution to a new branch (column-dialog) in my fork, so you can check it out: [Link](https://github.com/Lotec724/ngx-multi-sort-table/tree/column-dialog)

**Comment by Maxl94** [comment]
Thanks for your great effort. I really appreciate that. I will have a look at your implementation tomorrow.  Maybe I can help with the remaining problems.

**Comment by Maxl94** [comment]
@Lotec724 I had a look at your implementation. Looks good so far. The only thing I would improve is the position. Since the content of the dialog is dynamic large texts can get cut off at the side of the browser.

Here is my suggestion for a fix:
```position: { right: `22px`, top: `${button.offsetTop + button.offsetHeight}px` },```

With that fix, feel free to create a PR.

**Comment by Maxl94** [comment]
@Lotec724 I have improved the positioning of the dialog a little more. I also removed the `document.getById('..')`, because I think, this can lead to unsuspected behavior, when there are more than one tables on the same page.

**Comment by Lotec724** [comment]
Thank you very much! Good find with the id :)
