### ISSUE TITLE
defaultSortParams constructor parameter can't be used.

### ISSUE THREAD

**Issue by denpokoder** [Maxl94/ngx-multi-sort-table#44]
`defaultSortParams` can't be put as option in the TableData constructor call since it triggers the testing of `_displayedColumns` which haven't been set at that stage.

`if (options.defaultSortParams) {
                options.defaultSortParams.map(s => {                
                    if (!this._displayedColumns.includes(s)) {                    
                        throw Error('Provided sort parameter "${s}" is not a column.');                        
                    }                    
                });                
            }
`

**Comment by Maxl94** [comment]
Thanks for the report. I will have a look this week.

**Comment by Maxl94** [comment]
Fixed in version 0.5.3. Thanks for the report
