### ISSUE TITLE
Request for adding support of custom content in the chip list (Icons instead of "asc | desc" labels for example)

### ISSUE THREAD

**Issue by khalilof** [Maxl94/ngx-multi-sort-table#47]
Hello Max, 

first of all thank you for this awesome implementaion of multi-sorting. I am really enjoying it, however I have the case that I need to replace the labels in the chip list into icons (see attached example).

I am gonna create a pull request for this new feature, which will allow replacing anything desitred in the place of the column name and the direction indicator.  I hope you woudn't mind accepting it. 

Best Regards, 
khalilof
![icon-indicators](https://user-images.githubusercontent.com/1390784/116692890-61d20900-a9bd-11eb-8a22-49e43d987d0d.png)

**Comment by khalilof** [comment]
And this is the pull request for this contribution: 

https://github.com/Maxl94/ngx-multi-sort-table/pull/48

**Comment by Maxl94** [comment]
Thanks for your effort. 
I had a short look at the code, so far it looks fine. But will check out and test before creating a release. I plan this for this weekend or start of the next week,

**Comment by Maxl94** [comment]
Version is released

**Comment by khalilof** [comment]
@Maxl94  Thanks!
