### ISSUE TITLE
column-dialog can be outside of view, making items unreachable

### ISSUE THREAD

**Issue by Lotec724** [Maxl94/ngx-multi-sort-table#58]
Hello again,

I found an issue with the mat-dialog positioning implementation. If there are many entries in the column-list, some of them might not fit inside the viewport. However you can't scroll to these items either, because that's how mat-dialog is implemented. The same problem occurs if there is some content above the button, leaving not enough space in the viewport below to show all the items and again you can't scroll anymore. I made a branch in my fork with the first two commits showcasing the problem: https://github.com/Lotec724/ngx-multi-sort-table/tree/overlay You can also see it in the attached gif.
![GIF 22-06-2021 18-45-00](https://user-images.githubusercontent.com/26436299/122966969-40244b00-d38a-11eb-82d6-bc6c57ef8e11.gif)

The third commit is my proposed change to fix this issue. I decided to replace the mat-dialog with a [CDK Overlay](https://material.angular.io/cdk/overlay/overview) (thereby moving the functionality back into the settings.component). The overlay supports passing a positionStrategy in the constructor, which is handling exactly this problem. Otherwise it works pretty much the same. I decided to define a max-height of 70vh for the list, so a scrollbar appears inside the list if it gets too big. I also refactored some css properties to give them more intuitive names.

If you need any more info or would like to discuss the issue, let me know :)

**Comment by Maxl94** [comment]
HI @Lotec724,

first, sorry for the late response, I was on vacation. Thanks for your invested effort!

I see the issue, but I am pretty sure, that you can make the content of the dialog scrollable. But I think you have to set the height for the dialog or maybe have to add an element inside the dialog with a fixed height. I have done this before, but I currently don't remember how. Your solution looks like a good fix for the problem for now. 

Anyway, I currently think about replacing the column menu as a whole. I think it is not user-friendly, especial on smaller touch devices like phones. What do you think about replacing it (again) with a scrollable dialog for small devices and leaving the current solution for lager devices?

**Comment by Lotec724** [comment]
No worries :)

I tried making the dialog scrollable with CSS, which kind of worked, but still left the problem that depending on the scroll-state of the page, the dialog would be very small and kind of unusable, since it always renders below the trigger-button. If you have a proper solution for this with just CSS, I would also be happy with that.

You are right to say that this isn't friendly for mobile users as I was really only thinking about desktop applications. So improving the experience for small devices sounds like a good idea to me :)

**Comment by Maxl94** [comment]
Would you like to create a PR with your changes? I currently don't have the time to improve the table for mobile users. But I like to do this in the future. For now I want to fix the issure, you found, with a new release. Again thanks for your effort :)

**Comment by Lotec724** [comment]
Will do, should be ready tomorrow. Thank YOU for constantly improving this project :)

**Comment by Maxl94** [comment]
fixed with v0.7.2
