### ISSUE TITLE
Why does MatMultiSortTableDataSource not extend MatTableDataSource?

### ISSUE THREAD

**Issue by dickerpulli** [Maxl94/ngx-multi-sort-table#69]
Because of this missing inheritance the filter feature is not supported and has to be implemented by yourself. Will it be possible to extend MatTableDataSource?

**Comment by Maxl94** [comment]
I don't remember, why I deiced the extent the DataSource instead the MatTabelDataSource. The problem with these filter features from MatTableDataSource is, they only work if the data a provided by the client. If you load data from a server, the filter must be implemented server side. 

If you need filter feature and work with data available completely on the client, then I would recommend implementing the filters with in a service. Have a look at the DummySerice.

**Comment by dickerpulli** [comment]
Thank yi
